name: Broken Vue.js CI/CD Pipeline

on:
  push:
    branches:
      - master 
env:
  AWS_REGION: us-west-2  
  ECR_REPOSITORY: vue-app-prod  
  ECS_CLUSTER: vue-cluster  
  ECS_SERVICE: vue-service-prod  
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Deploy App to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Setup Node
        uses: actions/setup-node@v1 
        with:
          node-version: '16'  

      - name: Install NPM packages
        run: yarn install  

      - name: Build Vue App
        run: npm build  

      - name: Configure AWS Keys
        uses: aws-actions/configure-aws-credentials@v1  
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Login
        run: aws ecr get-login-password | docker login -u AWS --password-stdin  
      - name: Build and Push Docker Image
        run: |
          docker build -t vue-app .
          docker tag vue-app:latest <account>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/vue-app-prod:latest
          docker push <account>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/vue-app-prod:latest

      - name: Update ECS Service
        run: |
          aws ecs update \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --region ${{ env.AWS_REGION }}  
